### ISSUE TITLE
Deep Scan Variable/Scan Variable is not shown

### ISSUE THREAD

**Issue by trietptm** [igogo-x86/HexRaysPyTools#12]
Hi, I test HexRaysPyTools with this sample and it doesn't show the Deep Scan Variable/Scan Variable
https://github.com/trietptm/HexRaysPyTools/blob/master/tests/Box_1.exe

<img width="372" alt="box_1 1" src="https://user-images.githubusercontent.com/526959/39415178-6e6c1164-4c6a-11e8-812c-b148f0653547.png">

**Comment by trietptm** [comment]
I have found that if I use the "Reset pointer type" operation of IDA, the Deep Scan Variable/Scan Variable function of HexRaysPyTools will appear :) .

![image](https://user-images.githubusercontent.com/526959/39524304-b7f8145c-4e42-11e8-98a0-11f9910cafca.png)

**Comment by igogo-x86** [comment]
Hello! Originally I thought that it's better to scan only something similar to structure pointers. And in order to not produce bad results I restricted scanning to only types like `int`, `DWORD`, `PVOID` etc. But looks like `double *` and `WCHAR *` can also be structure pointers and that restriction is too strict. So in resent update I moved different settings to `IDADIR/cfg/HexRaysPyTools.cfg` file where you can find `scan_any_type` option. Variables with any types would be possible to scan after setting it value to True.

**Comment by trietptm** [comment]
Cool, it could Deep Scan Variable/Scan Variable now. I will let you know if I see other problems.
