### ISSUE TITLE
Can't unroll some nested code.

### ISSUE THREAD

**Issue by 2010kohtep** [igogo-x86/HexRaysPyTools#4]
I found a function, which pseudocode is not quite correct (there is still nested code in it).

Address: 0x102F61D0
Module: [client.dll.gz](https://github.com/igogo-x86/HexRaysPyTools/files/1058071/client.dll.gz)

![nested-code](https://user-images.githubusercontent.com/2564175/26880772-340ca7a4-4b9e-11e7-8bf8-f7aa5a66fbf8.png)

**Comment by igogo-x86** [comment]
There's nothing wrong with that output (at least not because of my plugin). If you are asking about automatic inversions, plugin makes them only when:
* `then` branch has 2+ expressions or 1 block
* `else` branch is absent
* `return` placed after `if`

It's imposible to automatically decide when to switch `then` and `else` branches. But I'm going to add new feature in a couple of days which allows to do it manually.

**Comment by skochinsky** [comment]
See `CMPFUNCS` in `hexrays.cfg`, no need for any plugins.

**Comment by igogo-x86** [comment]
Wow, never investigated that file. Nevetherless, it is now possible to switch then/else conditions manually (by selecting menu after clicking on 'if')
