### ISSUE TITLE
Recognize structures on global variables

### ISSUE THREAD

**Issue by lab313ru** [igogo-x86/HexRaysPyTools#7]
Now it works only at local variables (that are initiated with some input parameters).
But is it possible to add recognizing on global variables too?

Situation:
there is some global structure. Ida recognizes first dword to it as dword_123456. Full code is like this:
```
memset(dword_123456, 0, 0x78);
dword_123456 = 1;
dword_12345A = 4;
...
```

So, dword_12345A is just the second dword field of the structure.

**Comment by igogo-x86** [comment]
There's a reason why scanner (and recognizer) works only for structure pointers. It's tough to understand what is the size of the structure and whether we are addressing to a member or to another variable. For example, created on stack structure can have following appearence in decompiler:

![image](https://user-images.githubusercontent.com/22378463/27867444-56390b6e-61a2-11e7-8cc6-35ffd5aba298.png)

Though it also could be just five local variables and I don't the way to distinguish one option from another programmatically.

So that's why my plugin doesn't work with global structures or created on stack. May be some day if I meet tricky example I'll invent something but now overwhelming majority of structures i've seen are used by pointers.

**Comment by lab313ru** [comment]
But, if I know real size of the structure (for example, memset is used to clear it), can you implement recognizing for that?

**Comment by igogo-x86** [comment]
Recognition is build on scanning and scanning doesn't work for globals, so it's a little bit complicated. But if you know size why just don't try sorting local types and select structure? Or you can right click on 0x78 and use "Structures with given size" to make an attempt to find type (even different type libraries).

**Comment by lab313ru** [comment]
Problem is that structure is not defined. And sometimes structure size is huge (for example, 0x880 bytes). Defining every item is boring and time wasting. So, I want some tool, which will define such structures for me, and will recognize every item.

**Comment by Georgeto** [comment]
This project is open source, feel free to contribute ;)

**Comment by skochinsky** [comment]
just select the struct items and use IDA's own "Create struct from selection".
